server:
  port: 8090
spring:
  datasource:
    hikari:
      pool-name: SpringBootHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis-flex:
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: yuyuelai
      driver-class-name: com.mysql.cj.jdbc.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/nacos
      username: root
      password: yuyuelai
      driver-class-name: com.mysql.cj.jdbc.Driver
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      wiw:
        pinyee: debug